/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xyzlf_jni_demo_JniUtil */

#ifndef _Included_com_xyzlf_jni_demo_JniUtil
#define _Included_com_xyzlf_jni_demo_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xyzlf_jni_demo_JniUtil
 * Method:    getStringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xyzlf_jni_demo_JniUtil_getStringFromJni
  (JNIEnv *, jclass);

/*
 * Class:     com_xyzlf_jni_demo_JniUtil
 * Method:    uninstallListener
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xyzlf_jni_demo_JniUtil_uninstallListener
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
